version: '3.3'
services:
  admin-shop-postgres:
    image: postgres:13.7
    container_name: admin-shop-postgres
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - admin-shop-network
networks:
  admin-shop-network:
    driver: bridge
